config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :styles do
    member do
      put "like", to: "styles#upvote"
    end
  end

  root "styles#index"


end

app/models/style.rb
class Style < ActiveRecord::Base
  acts_as_votable
  belongs_to :user

  has_attached_file :image, styles: {medium: "300x300"}
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :styles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/styles_controller.rb
class StylesController < ApplicationController
  before_action :find_style, only: [:show, :edit, :update, :destroy, :upvote]
  before_action :authenticate_user!, except: [:index, :show]
  def index
    @styles = Style.all.order("created_at DESC")
  end

  def show
  end

  def new
    @style = current_user.styles.build
  end

  def create
    @style = current_user.styles.build(style_params)

    if @style.save
      redirect_to @style, notice: "Style successfully created."
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @style.update(style_params)
      redirect_to @style, notice: "Style was successfully updated."
    else
      render 'edit'
    end
  end

  def destroy
    @style.destroy
    redirect_to root_path
  end

  def upvote
    @style.upvote_by current_user
    redirect_to :back
  end

  private

  def style_params
    params.require(:style).permit(:title, :description, :image)
  end

  def find_style
    @style = Style.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/styles_helper.rb
module StylesHelper
end

app/views/layouts/application.html.haml
!!! 5
%html
%head
  %title Hairpin
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags
%body
  %nav.navbar.navbar-default
    .container
      .navbar-brand= link_to "Hairpin", root_path

      - if user_signed_in?
        %ul.nav.navbar-nav.navbar-right
          %li= link_to "New Style", new_style_path
          %li= link_to "Account", edit_user_registration_path
          %li= link_to "Sign Out", destroy_user_session_path, method: :delete
      -else
      %ul.nav.navbar-nav.navbar-right
        %li= link_to "Sign Up", new_user_registration_path
        %li= link_to "Sign In", new_user_session_path
    .container
      - flash.each do |name, msg|
        = content_tag :div, msg, class: "alert alert-info"
      = yield

app/views/styles/_form.html.haml
= simple_form_for @style, html: { multipart: true } do |f|
	- if @style.errors.any?
		#errors
			%h2
			= pluralize(@style.errors.count, "error")
			prevented this style from saving
			%ul
				- @style.errors.full_messages.each do |msg|
					%li= msg


	.form-group
		= f.input :title, input_html: { class: 'form-control' }

	.form-group
		= f.input :image, input_html: { class: 'form-control' }

	.form-group
		= f.input :description, input_html: { class: 'form-control' }

	= f.button :submit, class: "btn btn-primary"

app/views/styles/edit.html.haml
.col-md-6.col-md-offset-3
  .row
    .panel.panel-default
      .panel-heading
        %h1 Edit Style
      .panel-body
        %strong.center Current Image
        %br/
        = image_tag @style.image.url(:medium)
        = render 'form'

app/views/styles/index.html.haml
#styles.transitions-enabled
	- @styles.each do |style|
		.box.panel.panel-default
			= link_to (image_tag style.image.url), style
			%h2= link_to style.title, style
			

app/views/styles/new.html.haml
.col-md-6.col-md-offset-3
  .row
    .panel.panel-default
      .panel-heading
        %h1 New Form
      .panel-body
        = render 'form'

app/views/styles/show.html.haml
#style_show.row
  .col-md-8.col-md-offset-2
    .panel.panel-default
      .panel-heading.style_image
        = image_tag @style.image.url
      .panel-body
        %h1= @style.title
        %p.description= @style.description
      .panel-footer
        .row
          .col-md-6
            %p.user
              Styled by
              = @style.user.email
          .col-md-6
            .btn-group.pull-right
              = link_to like_style_path(@style), method: :put, class: "btn btn-default" do
                %span.glyphicon.glyphicon-heart
                = @style.get_upvotes.size
              - if user_signed_in?
                = link_to "Edit", edit_style_path, class: "btn btn-default"
                = link_to "Delete", style_path, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-default"